# Organize Imports and Dependencies

In [1]:
import pandas as pd

# Data Preprocessing and Cleaning

In [69]:
# Awards Data
df_awards = pd.read_csv('df_all_award_results_v3.csv')
df_awards = df_awards.drop_duplicates() # Drop duplicates

# Transactions Data
df_transactions = pd.read_csv('df_transactions_v3.csv')

In [70]:
df_awards.info()

<class 'pandas.core.frame.DataFrame'>
Index: 311182 entries, 0 to 1335644
Data columns (total 22 columns):
 #   Column                             Non-Null Count   Dtype
---  ------                             --------------   -----
 0   internal_id                        311182 non-null  int64
 1   Award ID                           311182 non-null  object
 2   generated_internal_id              311182 non-null  object
 3   Recipient Name                     311182 non-null  object
 4   Recipient DUNS Number              39304 non-null   float64
 5   recipient_id                       310673 non-null  object
 6   Award Amount                       311182 non-null  float64
 7   Awarding Agency                    311182 non-null  object
 8   Awarding Sub Agency                311182 non-null  object
 9   Funding Agency                     311182 non-null  object
 10  Funding Sub Agency                 311182 non-null  object
 11  Place of Performance City Code     0 non-null       float64
 12  Place of Performance State Code    304725 non-null  object
 13  Place of Performance Country Code  311182 non-null  object
 14  Place of Performance Zip5          304728 non-null  float64
 15  Last Modified Date                 311182 non-null  object
 16  Base Obligation Date               311182 non-null  object
 17  Start Date                         311179 non-null  object
 18  End Date                           311182 non-null  object
 19  Description                        311024 non-null  object
 20  awarding_agency_id                 311182 non-null  int64
 21  agency_slug                        311182 non-null  object
dtypes: float64(4), int64(2), object(16)
memory usage: 54.6+ MB

In [36]:
df_transactions.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 665939 entries, 0 to 665938
Data columns (total 13 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   Award ID                 665939 non-null  object
 1   internal_id              665939 non-null  int64
 2   generated_internal_id    665939 non-null  object
 3   Recipient Name           665939 non-null  object
 4   Action Date              665939 non-null  object
 5   Award Type               665939 non-null  object
 6   Mod                      665939 non-null  object
 7   Transaction Amount       665939 non-null  float64
 8   Transaction Description  665769 non-null  object
 9   Awarding Sub Agency      665939 non-null  object
 10  Awarding Agency          665939 non-null  object
 11  PSC                      665939 non-null  object
 12  NAICS                    665939 non-null  object
dtypes: float64(1), int64(1), object(11)
memory usage: 66.0+ MB

### Why are there so many more records in awards than transactions?
- There were duplicates in the data pull (around 3x). Drop duplicates using the `drop_duplicates` pandas function.

In [41]:
# The number of generated internal id's are essentially the same
print('generated_internal_id count')
print(len(df_transactions['generated_internal_id'].unique()))
print(len(df_awards['generated_internal_id'].unique()))

# Internal id functions the same way - same number of uniques
print('internal_id count')
print(len(df_transactions['internal_id'].unique()))
print(len(df_awards['internal_id'].unique()))

generated_internal_id count
311223
311182
internal_id count
311223
311182

In [59]:
print(min(df_transactions['Action Date']))
print(max(df_transactions['Action Date']))

2020-10-01
2026-04-18

In [65]:
df_awards

,internal_id,Award ID,generated_internal_id,Recipient Name,Recipient DUNS Number,recipient_id,Award Amount,Awarding Agency,Awarding Sub Agency,Funding Agency,...,Place of Performance State Code,Place of Performance Country Code,Place of Performance Zip5,Last Modified Date,Base Obligation Date,Start Date,End Date,Description,awarding_agency_id,agency_slug
0,291183257,70B04C20F00001359,CONT_AWD_70B04C20F00001359_7014_47QTCK18D0001_...,SCIENCE APPLICATIONS INTERNATIONAL CORPORATION,NaN,20af0683-f17d-1f8f-38ee-2f11bd124559-C,5.964741e+08,Department of Homeland Security,U.S. Customs and Border Protection,Department of Homeland Security,...,VA,USA,22315.0,2026-03-04 09:46:16,2020-09-29,2021-09-15,2026-09-14,U.S. CUSTOMS AND BORDER PROTECTION (CBP) OFFIC...,766,department-of-homeland-security
1,307343251,HSBP1012F00316,CONT_AWD_HSBP1012F00316_7014_GS00Q09BGD0060_4735,SCIENCE APPLICATIONS INTERNATIONAL CORP,NaN,900dcfe5-fb04-162f-2149-75b51d42021a-C,5.358694e+08,Department of Homeland Security,U.S. Customs and Border Protection,Department of Homeland Security,...,VA,USA,20190.0,2025-05-21 13:41:40,2012-09-12,2012-09-15,2017-09-14,"IT OPERATIONS AND MAINTENANCE, UPDATES, UPGRAD...",766,department-of-homeland-security
2,307799126,HSHQDC09J00001,CONT_AWD_HSHQDC09J00001_7001_HSHQDC06D00019_7001,INTERNATIONAL BUSINESS MACHINES CORPORATION,NaN,6ffc4386-853e-ef89-67e8-22c28ddcf15c-C,3.762819e+08,Department of Homeland Security,Office of Procurement Operations,Department of Homeland Security,...,DC,USA,20001.0,2023-07-18 16:09:13,2008-11-03,2008-11-03,2013-06-27,USCIS TRANSFORMATION PROGRAM SOLUTIONS ARCHITE...,766,department-of-homeland-security
3,307354270,HSBP1017C00137,CONT_AWD_HSBP1017C00137_7014_-NONE-_-NONE-,ACCENTURE FEDERAL SERVICES LLC,NaN,d41a6b8a-9d6a-0d28-7e24-989e31731aad-C,3.702511e+08,Department of Homeland Security,U.S. Customs and Border Protection,Department of Homeland Security,...,VA,USA,20598.0,2024-07-01 15:42:23,2017-09-30,2017-09-30,2023-06-30,DATA CENTER SUPPORT SERVICES FOR THE OFFICE OF...,766,department-of-homeland-security
4,291181988,70B04C18F00000071,CONT_AWD_70B04C18F00000071_7014_GS00Q09BGD0060...,SCIENCE APPLICATIONS INTERNATIONAL CORP,NaN,900dcfe5-fb04-162f-2149-75b51d42021a-C,3.687049e+08,Department of Homeland Security,U.S. Customs and Border Protection,Department of Homeland Security,...,VA,USA,22315.0,2023-01-27 17:45:34,2018-02-12,2018-03-14,2021-09-14,REQUIREMENT FOR UNITED STATES CUSTOMS AND BORD...,766,department-of-homeland-security
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1335649,292210541,9523ZY25F0018,CONT_AWD_9523ZY25F0018_9507_47QTCB21D0061_4732,SHIVOY INC.,NaN,9b0f702d-76a1-46d0-699f-eff92fb07a72-C,6.031824e+05,Commodity Futures Trading Commission,Commodity Futures Trading Commission,Commodity Futures Trading Commission,...,DC,USA,20581.0,2026-04-17 13:12:41,2025-03-28,2025-04-01,2027-03-31,PRISM SUPPORT SERVICES,1129,commodity-futures-trading-commission
1335650,292210544,9523ZY25F0021,CONT_AWD_9523ZY25F0021_9507_NNG15SD07B_8000,REGENCY CONSULTING INC,NaN,b6010741-8577-b3d7-bed6-b9fcff3518e1-C,1.305839e+05,Commodity Futures Trading Commission,Commodity Futures Trading Commission,Commodity Futures Trading Commission,...,DC,USA,20581.0,2026-04-08 08:13:45,2025-04-10,2025-04-13,2027-04-12,SOLARWINDS RENEWAL,1129,commodity-futures-trading-commission
1335651,292210546,9523ZY25F0023,CONT_AWD_9523ZY25F0023_9507_NNG15SD74B_8000,SOFTWARE INFORMATION RESOURCE CORP.,NaN,2a71ed51-39c8-082f-31a0-f31d55a0a651-C,2.075112e+04,Commodity Futures Trading Commission,Commodity Futures Trading Commission,Commodity Futures Trading Commission,...,DC,USA,20581.0,2026-04-16 14:38:02,2025-04-21,2025-04-21,2027-04-20,OXYGEN FORENSIC DETECTIVE SMS RENEWAL,1129,commodity-futures-trading-commission
1335652,356789928,9523ZY26F0020,CONT_AWD_9523ZY26F0020_9507_NNG15SD26B_8000,"THUNDERCAT TECHNOLOGY, LLC",NaN,dbceb126-f729-60e7-d55a-ba235f519653-C,1.713816e+04,Commodity Futures Trading Commission,Commodity Futures Trading Commission,Commodity Futures Trading Commission,...,IL,USA,60604.0,2026-04-03 11:05:48,2026-04-03,2026-04-03,2026-06-02,CRESTRON EQUIPMENT,1129,commodity-futures-trading-commission
1335653,356948944,9523ZY26F0022,CONT_AWD_9523ZY26F0022_9507_NNG15SC69B_8000,DYNAMIC SYSTEMS INC,NaN,b3f4a970-826f-4d84-8f0f-3b66cffeb27d-C,1.620200e+04,Commodity Futures Trading Commission,Commodity Futures Trading Commission,Commodity Futures Trading Commission,...,DC,USA,20581.0,2026-04-13 14:07:23,2026-04-09,2026-05-20,2027-05-19,ORACLE DATA INTEGRATOR (ODI) ENTERPRISE LICENS...,1129,commodity-futures-trading-commission

In [100]:
# Calculate aggregate statistics at parent (Award ID) level
df_t_gb = df_transactions.groupby('generated_internal_id').agg(
                                                    {'Transaction Amount' : 'sum',
                                                     'Award ID' : 'count',
                                                    'Mod' : 'count'}).reset_index()

In [101]:
# Merge to df_awards
df_merge = pd.merge(df_awards, df_t_gb, how = 'left', on = 'generated_internal_id')

### Create a Binary Column for Overspend

In [104]:
df_merge.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 311182 entries, 0 to 311181
Data columns (total 26 columns):
 #   Column                             Non-Null Count   Dtype
---  ------                             --------------   -----
 0   internal_id                        311182 non-null  int64
 1   Award ID_x                         311182 non-null  object
 2   generated_internal_id              311182 non-null  object
 3   Recipient Name                     311182 non-null  object
 4   Recipient DUNS Number              39304 non-null   float64
 5   recipient_id                       310673 non-null  object
 6   Award Amount                       311182 non-null  float64
 7   Awarding Agency                    311182 non-null  object
 8   Awarding Sub Agency                311182 non-null  object
 9   Funding Agency                     311182 non-null  object
 10  Funding Sub Agency                 311182 non-null  object
 11  Place of Performance City Code     0 non-null       float64
 12  Place of Performance State Code    304725 non-null  object
 13  Place of Performance Country Code  311182 non-null  object
 14  Place of Performance Zip5          304728 non-null  float64
 15  Last Modified Date                 311182 non-null  object
 16  Base Obligation Date               311182 non-null  object
 17  Start Date                         311179 non-null  object
 18  End Date                           311182 non-null  object
 19  Description                        311024 non-null  object
 20  awarding_agency_id                 311182 non-null  int64
 21  agency_slug                        311182 non-null  object
 22  Transaction Amount                 311162 non-null  float64
 23  Award ID_y                         311162 non-null  float64
 24  Mod                                311162 non-null  float64
 25  is_democrat                        311182 non-null  int64
dtypes: float64(7), int64(3), object(16)
memory usage: 61.7+ MB

In [130]:
df_merge[['Transaction Amount', 'Award Amount']]
df_merge['overspend'] = df_merge['Transaction Amount'] > df_merge['Award Amount']
df_merge['overspend_amount'] = df_merge['Transaction Amount'] - df_merge['Award Amount']

df_merge[df_merge['overspend_amount'] > 1]

,internal_id,Award ID_x,generated_internal_id,Recipient Name,Recipient DUNS Number,recipient_id,Award Amount,Awarding Agency,Awarding Sub Agency,Funding Agency,...,End Date,Description,awarding_agency_id,agency_slug,Transaction Amount,Award ID_y,Mod,is_democrat,overspend,overspend_amount
20462,278257129,15F06719F0003578,CONT_AWD_15F06719F0003578_1549_GS35F0655W_4730,"QBASE, LLC",NaN,6f04ece4-7912-04e0-9881-50a4bc17fba7-C,9269200.07,Department of Justice,Federal Bureau of Investigation,Department of Justice,...,2024-10-02,TICTU SERVICES,252,department-of-justice,9298037.86,7.0,7.0,0,True,28837.79
42699,349057622,W56JSR19F0054,CONT_AWD_W56JSR19F0054_9700_W15P7T12DE005_9700,"MANTECH ADVANCED SYSTEMS INTERNATIONAL, INC.",NaN,ceac1920-9ceb-17a6-9bf7-026817a02917-C,4317199.11,Department of Defense,Department of the Army,Department of Defense,...,2024-09-25,IGF::CL::IGF THIS TASK ORDER IS AWARDED AS A ...,1173,department-of-defense,24160848.43,41.0,41.0,0,True,19843649.32
43299,298461333,FA821820F0029,CONT_AWD_FA821820F0029_9700_47QTCA20D006Y_4732,"T-METRICS, LLC",NaN,2cd5f305-311b-819d-7e25-29c9f00c22e1-C,3470840.19,Department of Defense,Department of the Air Force,Department of Defense,...,2025-07-16,TASK ORDER TO SUPPORT CONSOLIDATED OPERATOR AN...,1173,department-of-defense,5733707.40,6.0,6.0,0,True,2262867.21
46727,349717802,W9128Z20F0017,CONT_AWD_W9128Z20F0017_9700_W9128Z11D0006_9700,"EMPOWER AI, INC.",620864504.0,4ba55072-0228-c003-d8a4-067938e3a80a-C,779926.86,Department of Defense,Department of the Army,Department of Defense,...,2022-06-18,PROVIDE DEPARTMENT OF DEFENSE (DOD)RISK MANAGE...,1173,department-of-defense,1304135.45,13.0,13.0,0,True,524208.59
52075,307876631,HT001519P0015,CONT_AWD_HT001519P0015_9700_-NONE-_-NONE-,APPLIED SOFTWARE INC,NaN,c8ae279a-02c3-4942-91a7-a5f3c2ecfdf4-C,123345.00,Department of Defense,Defense Health Agency,Department of Defense,...,2024-09-29,MAGVIEW ANNUAL SOFTWARE MAINTENANCE FOR FORT B...,1173,department-of-defense,186610.00,3.0,3.0,0,True,63265.00
53059,298176830,FA481419FA155,CONT_AWD_FA481419FA155_9700_GS35F0288W_4730,COMPU DYNAMICS LLC,NaN,40903d18-c98f-56cd-6d15-7ddb975571d3-C,93375.00,Department of Defense,Department of the Air Force,Department of Defense,...,2024-05-31,PREVENTATIVE MAINTENANCE OF THE UNINTERRUPTED ...,1173,department-of-defense,378355.15,5.0,5.0,0,True,284980.15
60896,298584848,FA872319F9002,CONT_AWD_FA872319F9002_9700_NNG15SC38B_8000,"TRACE3 GOVERNMENT, LLC",NaN,9f9e261d-84e3-778c-24d5-2f73301919e6-C,7500.00,Department of Defense,Department of the Air Force,Department of Defense,...,2022-10-31,CYBERSECURITY ASSESSMENTS OF GROUND BASED RADA...,1173,department-of-defense,702001.76,5.0,5.0,0,True,694501.76
60979,306420215,HC101318FD278,CONT_AWD_HC101318FD278_9700_HC101318A0001_9700,"SATCOM DIRECT GOVERNMENT, LLC",NaN,138a943e-a30b-cbd1-43f5-85662e6862bd-C,7034.93,Department of Defense,Defense Information Systems Agency,Department of Defense,...,2024-04-22,IGF::OT::IGF SDCC000121EBM INMARSAT SWIFT BROA...,1173,department-of-defense,7276.93,7.0,7.0,0,True,242.00
86675,306441839,HC101322FC694,CONT_AWD_HC101322FC694_9700_HC101318A0004_9700,MCI COMMUNICATIONS SERVICES LLC,NaN,108b454d-a668-8157-acbc-d6947e8e52dc-C,254.00,Department of Defense,Defense Information Systems Agency,Department of Defense,...,2027-03-15,VERB005425EBM - VOICE SERVICE LONG DISTANCE - ...,1173,department-of-defense,508.00,3.0,3.0,1,True,254.00
86705,306441720,HC101322FC575,CONT_AWD_HC101322FC575_9700_HC101318A0004_9700,MCI COMMUNICATIONS SERVICES LLC,NaN,108b454d-a668-8157-acbc-d6947e8e52dc-C,254.00,Department of Defense,Defense Information Systems Agency,Department of Defense,...,2027-03-15,VERB005372EBM LONG DISTANCE SWITCHED,1173,department-of-defense,508.00,3.0,3.0,1,True,254.00
86754,306441650,HC101322FC503,CONT_AWD_HC101322FC503_9700_HC101318A0004_9700,MCI COMMUNICATIONS SERVICES LLC,NaN,108b454d-a668-8157-acbc-d6947e8e52dc-C,254.00,Department of Defense,Defense Information Systems Agency,Department of Defense,...,2025-03-15,VERB005322EBM LONG DISTANCE SWITCHED,1173,department-of-defense,508.00,2.0,2.0,1,True,254.00
86759,306441641,HC101322FC493,CONT_AWD_HC101322FC493_9700_HC101318A0004_9700,MCI COMMUNICATIONS SERVICES LLC,NaN,108b454d-a668-8157-acbc-d6947e8e52dc-C,254.00,Department of Defense,Defense Information Systems Agency,Department of Defense,...,2027-03-15,"VERB005317EBM, LONG DISTANCE SWITCHED",1173,department-of-defense,508.00,3.0,3.0,1,True,254.00
86846,306441506,HC101322FC354,CONT_AWD_HC101322FC354_9700_HC101318A0004_9700,MCI COMMUNICATIONS SERVICES LLC,NaN,108b454d-a668-8157-acbc-d6947e8e52dc-C,254.00,Department of Defense,Defense Information Systems Agency,Department of Defense,...,2027-03-15,VERB005227EBM - LONG DISTANCE SWITCHED,1173,department-of-defense,508.00,3.0,3.0,1,True,254.00
86854,306441494,HC101322FC342,CONT_AWD_HC101322FC342_9700_HC101318A0004_9700,MCI COMMUNICATIONS SERVICES LLC,NaN,108b454d-a668-8157-acbc-d6947e8e52dc-C,254.00,Department of Defense,Defense Information Systems Agency,Department of Defense,...,2027-03-15,VERB005218EBM - LONG DISTANCE SWITCHED,1173,department-of-defense,508.00,3.0,3.0,1,True,254.00
86864,306441480,HC101322FC327,CONT_AWD_HC101322FC327_9700_HC101318A0004_9700,MCI COMMUNICATIONS SERVICES LLC,NaN,108b454d-a668-8157-acbc-d6947e8e52dc-C,254.00,Department of Defense,Defense Information Systems Agency,Department of Defense,...,2027-03-15,"VERB005207EBM, LONG DISTANCE SWITCHED",1173,department-of-defense,508.00,3.0,3.0,1,True,254.00
86933,306441354,HC101322FC196,CONT_AWD_HC101322FC196_9700_HC101318A0004_9700,MCI COMMUNICATIONS SERVICES LLC,NaN,108b454d-a668-8157-acbc-d6947e8e52dc-C,254.00,Department of Defense,Defense Information Systems Agency,Department of Defense,...,2023-10-06,VERB005133EBM LONG DISTANCE SWITCHED.,1173,department-of-defense,508.00,3.0,3.0,1,True,254.00
87052,306441148,HC101322FB981,CONT_AWD_HC101322FB981_9700_HC101318A0004_9700,MCI COMMUNICATIONS SERVICES LLC,NaN,108b454d-a668-8157-acbc-d6947e8e52dc-C,254.00,Department of Defense,Defense Information Systems Agency,Department of Defense,...,2023-07-28,DELIVERY/TASK ORDER FOR VERB005009EBM. VOICE S...,1173,department-of-defense,508.00,3.0,3.0,1,True,254.00
87185,306440931,HC101322FB749,CONT_AWD_HC101322FB749_9700_HC101318A0004_9700,MCI COMMUNICATIONS SERVICES LLC,NaN,108b454d-a668-8157-acbc-d6947e8e52dc-C,254.00,Department of Defense,Defense Information Systems Agency,Department of Defense,...,2023-08-22,VERB004861EBM - VOICE SERVICE LONG DISTANCE - ...,1173,department-of-defense,508.00,5.0,5.0,1,True,254.00
87193,306440897,HC101322FB715,CONT_AWD_HC101322FB715_9700_HC101318A0004_9700,MCI COMMUNICATIONS SERVICES LLC,NaN,108b454d-a668-8157-acbc-d6947e8e52dc-C,254.00,Department of Defense,Defense Information Systems Agency,Department of Defense,...,2023-10-19,VERB004853EBM - VOICE SERVICE LONG DISTANCE - ...,1173,department-of-defense,508.00,3.0,3.0,1,True,254.00
87283,306440761,HC101322FB565,CONT_AWD_HC101322FB565_9700_HC101318A0004_9700,MCI COMMUNICATIONS SERVICES LLC,NaN,108b454d-a668-8157-acbc-d6947e8e52dc-C,254.00,Department of Defense,Defense Information Systems Agency,Department of Defense,...,2027-03-15,VERB004745EBM VOICE SERVICE LONG DISTANCE - SW...,1173,department-of-defense,508.00,4.0,4.0,1,True,254.00
87305,306440728,HC101322FB529,CONT_AWD_HC101322FB529_9700_HC101318A0004_9700,MCI COMMUNICATIONS SERVICES LLC,NaN,108b454d-a668-8157-acbc-d6947e8e52dc-C,254.00,Department of Defense,Defense Information Systems Agency,Department of Defense,...,2027-03-15,VERB004722EBM LONG DISTANCE SWITCHED,1173,department-of-defense,508.00,3.0,3.0,1,True,254.00
87466,306440514,HC101322FB277,CONT_AWD_HC101322FB277_9700_HC101318A0004_9700,MCI COMMUNICATIONS SERVICES LLC,NaN,108b454d-a668-8157-acbc-d6947e8e52dc-C,254.00,Department of Defense,Defense Information Systems Agency,Department of Defense,...,2027-03-15,"VERB004557EBM, VSLD-S",1173,department-of-defense,508.00,3.0,3.0,1,True,254.00
87499,306440438,HC101322FB199,CONT_AWD_HC101322FB199_9700_HC101318A0004_9700,MCI COMMUNICATIONS SERVICES LLC,NaN,108b454d-a668-8157-acbc-d6947e8e52dc-C,254.00,Department of Defense,Defense Information Systems Agency,Department of Defense,...,2023-04-17,VERB004523EBM VOICE SERVICE LONG DISTANCE-SWIT...,1173,department-of-defense,508.00,4.0,4.0,1,True,254.00
87581,306440308,HC101322FB055,CONT_AWD_HC101322FB055_9700_HC101318A0004_9700,MCI COMMUNICATIONS SERVICES LLC,NaN,108b454d-a668-8157-acbc-d6947e8e52dc-C,254.00,Department of Defense,Defense Information Systems Agency,Department of Defense,...,2022-05-17,DELIVERY/TASK ORDER FOR VERB004435EBM. VOICE S...,1173,department-of-defense,508.00,4.0,4.0,1,True,254.00
89089,349675274,W9127822P0080,CONT_AWD_W9127822P0080_9700_-NONE-_-NONE-,HYDROPOWER RESEARCH INSTITUTE,NaN,f02767a0-1118-204f-71b6-5290f5732576-C,200000.00,Department of Defense,Department of the Army,Corps of Engineers - Civil Works,...,2023-05-31,ANNUAL MEMBERSHIP TO HRI,1173,department-of-defense,400000.00,2.0,2.0,1,True,200000.00
93345,306443614,HC101322FE631,CONT_AWD_HC101322FE631_9700_HC101318A0004_9700,MCI COMMUNICATIONS SERVICES LLC,NaN,108b454d-a668-8157-acbc-d6947e8e52dc-C,254.00,Department of Defense,Defense Information Systems Agency,Department of Defense,...,2027-03-15,"VERB006077EBM, LONG DISTANCE SWITCHED",1173,department-of-defense,508.00,3.0,3.0,1,True,254.00
112367,306449080,HC101323FB382,CONT_AWD_HC101323FB382_9700_HC101318A0004_9700,MCI COMMUNICATIONS SERVICES LLC,NaN,108b454d-a668-8157-acbc-d6947e8e52dc-C,254.00,Department of Defense,Defense Information Systems Agency,Department of Defense,...,2027-03-15,VERB008796EBM - LONG DISTANCE SWITCHED,1173,department-of-defense,508.00,3.0,3.0,1,True,254.00
112578,306448348,HC101323FA609,CONT_AWD_HC101323FA609_9700_HC101318A0004_9700,MCI COMMUNICATIONS SERVICES LLC,NaN,108b454d-a668-8157-acbc-d6947e8e52dc-C,254.00,Department of Defense,Defense Information Systems Agency,Department of Defense,...,2027-03-15,VERB008454EBM VOICE SERVICE LONG DISTANCE - SW...,1173,department-of-defense,508.00,3.0,3.0,1,True,254.00
112733,306447836,HC101323FA080,CONT_AWD_HC101323FA080_9700_HC101318A0004_9700,MCI COMMUNICATIONS SERVICES LLC,NaN,108b454d-a668-8157-acbc-d6947e8e52dc-C,254.00,Department of Defense,Defense Information Systems Agency,Department of Defense,...,2027-03-15,VERB008202EBM LONG DISTANCE SWITCHED VOICE SER...,1173,department-of-defense,508.00,3.0,3.0,1,True,254.00
117141,306451319,HC101323FD859,CONT_AWD_HC101323FD859_9700_HC101318A0004_9700,MCI COMMUNICATIONS SERVICES LLC,NaN,108b454d-a668-8157-acbc-d6947e8e52dc-C,254.00,Department of Defense,Defense Information Systems Agency,Department of Defense,...,2024-04-09,VERB009972EBM - TOLL FREE SERVICE DEDICATED,1173,department-of-defense,508.00,4.0,4.0,1,True,254.00
117211,306451094,HC101323FD624,CONT_AWD_HC101323FD624_9700_HC101318A0004_9700,MCI COMMUNICATIONS SERVICES LLC,NaN,108b454d-a668-8157-acbc-d6947e8e52dc-C,254.00,Department of Defense,Defense Information Systems Agency,Department of Defense,...,2027-03-15,VERB009881EBM VSLD-S,1173,department-of-defense,508.00,4.0,4.0,1,True,254.00
117225,306451054,HC101323FD584,CONT_AWD_HC101323FD584_9700_HC101318A0004_9700,MCI COMMUNICATIONS SERVICES LLC,NaN,108b454d-a668-8157-acbc-d6947e8e52dc-C,254.00,Department of Defense,Defense Information Systems Agency,Department of Defense,...,2027-03-15,VERB009859EBM - LONG DISTANCE SWITCHED,1173,department-of-defense,508.00,3.0,3.0,1,True,254.00
117255,306450896,HC101323FD421,CONT_AWD_HC101323FD421_9700_HC101318A0004_9700,MCI COMMUNICATIONS SERVICES LLC,NaN,108b454d-a668-8157-acbc-d6947e8e52dc-C,254.00,Department of Defense,Defense Information Systems Agency,Department of Defense,...,2027-03-15,VERB009802EBM - LONG DISTANCE SWITCHED,1173,department-of-defense,508.00,3.0,3.0,1,True,254.00
117352,306450673,HC101323FD186,CONT_AWD_HC101323FD186_9700_HC101318A0004_9700,MCI COMMUNICATIONS SERVICES LLC,NaN,108b454d-a668-8157-acbc-d6947e8e52dc-C,254.00,Department of Defense,Defense Information Systems Agency,Department of Defense,...,2027-03-15,VERB009696EBM - LONG DISTANCE SWITCHED,1173,department-of-defense,508.00,3.0,3.0,1,True,254.00
117438,306450555,HC101323FD060,CONT_AWD_HC101323FD060_9700_HC101318A0004_9700,MCI COMMUNICATIONS SERVICES LLC,NaN,108b454d-a668-8157-acbc-d6947e8e52dc-C,254.00,Department of Defense,Defense Information Systems Agency,Department of Defense,...,2027-03-15,VERB009606EBM LONG DISTANCE SWITCHED VOICE SER...,1173,department-of-defense,508.00,3.0,3.0,1,True,254.00
117458,306450531,HC101323FD036,CONT_AWD_HC101323FD036_9700_HC101318A0004_9700,MCI COMMUNICATIONS SERVICES LLC,NaN,108b454d-a668-8157-acbc-d6947e8e52dc-C,254.00,Department of Defense,Defense Information Systems Agency,Department of Defense,...,2027-03-15,VERB009586EBM LONG DISTANCE SWITCHED VOICE SER...,1173,department-of-defense,508.00,3.0,3.0,1,True,254.00
117471,306450456,HC101323FC958,CONT_AWD_HC101323FC958_9700_HC101318A0004_9700,MCI COMMUNICATIONS SERVICES LLC,NaN,108b454d-a668-8157-acbc-d6947e8e52dc-C,254.00,Department of Defense,Defense Information Systems Agency,Department of Defense,...,2025-08-28,VERB009571EBM LONG DISTANCE SWITCHED VOICE SER...,1173,department-of-defense,508.00,5.0,5.0,1,True,254.00
286371,277739784,140A1619F0053,CONT_AWD_140A1619F0053_1450_GS00Q17GWD2209_4732,NATIVE HAWAIIAN VETERANS LLC,NaN,874a7684-18b3-4064-480c-120b8f62b9df-C,6101453.50,Department of the Interior,Bureau of Indian Affairs and Bureau of Indian ...,Department of the Interior,...,2024-09-20,IGF::CL::IGF INFORMATION TECHNOLOGY USER SUPPO...,209,department-of-the-interior,22189974.64,24.0,24.0,0,True,16088521.14

### Create a Binary Column for Incumbent (is_democrat)

In [103]:
# Create Democrat / Republican column
def is_democrat(date_input):
    # Biden term: Jan 20, 2021 to Jan 20, 2025
    biden_start = pd.Timestamp('2021-01-20')
    biden_end = pd.Timestamp('2025-01-20')
    
    # Check if the row's date falls within the Biden administration
    if biden_start <= pd.Timestamp(date_input) < biden_end:
        return 1
    else:
        return 0
    
df_merge['is_democrat'] = df_merge['Base Obligation Date'].apply(lambda row : is_democrat(row))

### Create Modification within 1 Year Variable

In [91]:
df_transactions['Action Date'] = pd.to_datetime(df_transactions['Action Date'])

# Ensures first value for first mod date is in each row
df_transactions['first_mod_date'] = df_transactions.groupby('generated_internal_id')['Action Date']\
    .transform(lambda x: x[df_transactions.loc[x.index, 'Mod'] == '0'].min())

# Creates flag to ensure a Non base funding mod (!= 0) is within 365 dat=ys
df_transactions['is_within_year'] = (
    ((df_transactions['Action Date'] >= df_transactions['first_mod_date']) & 
    (df_transactions['Action Date'] <= df_transactions['first_mod_date'] + pd.Timedelta(days=365))) # Leq 365 days
    & df_transactions['Mod'] != 0 # Not base funding
)

# 4. Final Result: One row per ID
has_mod_within_year = df_transactions.groupby('generated_internal_id')['is_within_year'].any().reset_index()
has_mod_within_year['is_within_year'] = has_mod_within_year['is_within_year'].astype(int)

# Feature Engineering

In [ ]:
# Create a binary column (overspend) if a contract will cost more than the original base award (total award amount > base award amount).